# Generated by Django 2.1.3 on 2018-11-12 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxwell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='maxwell.DataSet'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
